name = "product-oline-fps-game"
main = "_worker.js"
compatibility_date = "2026-01-29"

[site]
bucket = "."

[durable_objects]
bindings = [
  { name = "GAME_ROOM", class_name = "GameRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]
